"""empty message

Revision ID: 62f5143697a5
Revises: cc19837e7ee8
Create Date: 2024-01-17 13:10:53.267644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f5143697a5'
down_revision = 'cc19837e7ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platfroms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_for', sa.String(length=100), nullable=True))

    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('platfroms', schema=None) as batch_op:
        batch_op.drop_column('valid_for')

    # ### end Alembic commands ###
