"""empty message

Revision ID: cc19837e7ee8
Revises: 5099b4f700d3
Create Date: 2024-01-11 11:15:02.265879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc19837e7ee8'
down_revision = '5099b4f700d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
