"""empty message

Revision ID: fa7fb2f1f6ce
Revises: 62f5143697a5
Create Date: 2024-01-17 15:49:04.737723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7fb2f1f6ce'
down_revision = '62f5143697a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versions', sa.String(), nullable=True))

    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softwares', schema=None) as batch_op:
        batch_op.drop_column('versions')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('versions')

    # ### end Alembic commands ###
